name: repsim
channels:
  - defaults
dependencies:
  - appnope=0.1.4=py312hca03da5_0
  - asttokens=3.0.0=py312hca03da5_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.9.9=hca03da5_0
  - cmake=4.1.2=hdb7c5fe_0
  - comm=0.2.1=py312hca03da5_0
  - debugpy=1.8.16=py312h0962b89_0
  - decorator=5.2.1=py312hca03da5_0
  - executing=2.2.1=py312hca03da5_0
  - expat=2.7.1=h313beb8_0
  - ipykernel=6.30.1=py312hca03da5_0
  - ipython=9.5.0=py312hca03da5_0
  - ipython_pygments_lexers=1.1.1=py312hca03da5_0
  - jedi=0.19.2=py312hca03da5_0
  - jupyter_client=8.6.3=py312hca03da5_0
  - jupyter_core=5.8.1=py312hca03da5_0
  - libcurl=8.15.0=hcdd2897_0
  - libcxx=20.1.8=hd7fd590_1
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.30=hf2bb037_0
  - libsodium=1.0.20=h897f8a9_0
  - libssh2=1.11.1=h3e2b118_0
  - libuv=1.48.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - matplotlib-inline=0.1.7=py312hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py312hca03da5_0
  - ninja=1.12.1=hca03da5_0
  - ninja-base=1.12.1=h48ca7d4_0
  - openssl=3.0.18=h9b4081a_0
  - packaging=25.0=py312hca03da5_1
  - parso=0.8.4=py312hca03da5_0
  - pathspec=0.12.1=py312hca03da5_0
  - pexpect=4.9.0=py312hca03da5_0
  - pip=25.2=pyhc872135_1
  - platformdirs=4.3.7=py312hca03da5_0
  - prompt-toolkit=3.0.52=py312hca03da5_0
  - prompt_toolkit=3.0.52=hd3eb1b0_0
  - psutil=7.0.0=py312h254cc4a_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=py312hca03da5_0
  - pybind11=2.13.6=py312h48ca7d4_1
  - pybind11-global=2.13.6=py312h48ca7d4_1
  - pygments=2.19.1=py312hca03da5_0
  - python=3.12.12=h2bfc596_1
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - pyzmq=27.1.0=py312h854a7ef_0
  - readline=8.3=h0b18652_0
  - rhash=1.4.6=hed31dab_0
  - scikit-build-core=0.11.6=py312h27d5b7f_0
  - setuptools=80.9.0=py312hca03da5_0
  - six=1.17.0=py312hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=py312hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py312h80987f9_0
  - traitlets=5.14.3=py312hca03da5_0
  - wcwidth=0.2.13=py312hca03da5_0
  - wheel=0.45.1=py312hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h2c7f8f0_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - attrs==25.4.0
      - build==1.3.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - docutils==0.22.2
      - fastjsonschema==2.21.2
      - fonttools==4.60.1
      - id==1.5.0
      - idna==3.11
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.3.0
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - keyring==25.6.0
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - nbclient==0.10.2
      - nbformat==5.10.4
      - nh3==0.3.2
      - numpy==2.3.4
      - pandas==2.3.3
      - pillow==12.0.0
      - pyparsing==3.2.5
      - pyproject-hooks==1.2.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - readme-renderer==44.0
      - referencing==0.37.0
      - repsim==0.1.5
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==14.2.0
      - rpds-py==0.28.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - threadpoolctl==3.6.0
      - twine==6.2.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
prefix: /Users/kyou/miniconda3/envs/repsim
