project:
  type: website
  output-dir: _site

website:
  title: "repsim"
  navbar:
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Install"
        href: install.qmd
      - text: "Getting Started"
        href: getting-started.qmd
      - text: "API"
        href: api/index.qmd        # <â€” landing page for API docs
  sidebar:
    - id: api
      title: "API Reference"
      contents:
        - text: "API Home"
          href: api/index.qmd
        - section: "CCA"
          contents:
            - api/family_cca/cca.qmd
            - api/family_cca/pwcca.qmd
            - api/family_cca/svcca.qmd
        - section: "Utilities"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-copy: true
    anchor-sections: true

# run code and cache outputs
execute:
  freeze: auto
  cache: true
  echo: true
  python: /Users/kyou/miniconda3/envs/repsim/bin/python
  r: /usr/local/bin/R
  RETICULATE_PYTHON: /Users/kyou/miniconda3/envs/repsim/bin/python